apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass

metadata:
  name: default

spec:
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  role: project7-eks-node-group-role

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: project7-eks

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: project7-eks

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true

  tags:
    Name: project7-karpenter-node