apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
---
# Extra Services required by the Argo Rollout canary/blueGreen strategies.
# The rollout controller manages which pods these select at runtime.
apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend-canary
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend-preview
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
