apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "taskflow.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskflow.backend.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.backend.service.targetPort }}"
    spec:
      containers:
        {{- include "taskflow.backend.container" . | nindent 8 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
