apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-backend-config
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "taskflow.backend.selectorLabels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.backend.env.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  CORS_ORIGINS: {{ .Values.backend.env.CORS_ORIGINS | quote }}
