apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    {{- include "taskflow.frontend.selectorLabels" . | nindent 4 }}
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "taskflow.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskflow.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        {{- include "taskflow.frontend.container" . | nindent 8 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
